CREATE DATABASE LOGIN;
USE LOGIN;

CREATE TABLE USUARIOS(
 ID INT AUTO_INCREMENT PRIMARY KEY,
 EMAIL VARCHAR(255) NOT NULL UNIQUE,
 SENHA VARCHAR(255) NOT NULL 
);

INSERT INTO USUARIOS
VALUES
(DEFAULT, 'sit.leticia@barueri.sp.gov.br', 'senha!');

SELECT * FROM  USUARIOS;
