CREATE DATABASE LOGIN;
USE LOGIN;

CREATE TABLE USUARIOS(
 ID INT AUTO_INCREMENT PRIMARY KEY,
 EMAIL VARCHAR(255) NOT NULL UNIQUE,
 SENHA VARCHAR(255) NOT NULL 
);

INSERT INTO USUARIOS
VALUES
(DEFAULT, 'sit.claudia@barueri.sp.gov.br', '$2b$10$NOTLQv1dixWM.ALG4X0c7uz4ZtQ7WywkJeBPeVynxtSRXUvi3QBee');


SELECT * FROM  USUARIOS;

INSERT INTO USUARIOS
VALUES
(DEFAULT, 'sit.leticia@barueri.sp.gov.br', '$2b$10$vyks2ubjGhCjdTUhQnp8QOUulhxjYordra/ij8OGvvquKgeY4obBK');

SHOW TABLES;

UPDATE USUARIOS
SET SENHA = '$2b$10$omMQvSjXp.Jk4suo.KwcruHBwVkDDqdqW89U7wNwUdJoNlpb.GpVy'
WHERE EMAIL = 'sit.claudia@barueri.sp.gov.br';

